In [69]:
import pandas as pd
import numpy as np
import os
import re

pd.set_option('display.max_rows', 50)

In [70]:
# CALCULATE BUDGETS FOR EACH AREA

month = '2022-06'

init_budget = {}

init_budget['governance'] = 2
init_budget['curation'] = 2.5
init_budget['marketing & pr'] = 2.5
init_budget['community'] = 1.5
init_budget['finance'] = 1.5

perf_tranche = {}

perf_tranche['governance'] =  0.4
perf_tranche['curation'] = 0.4
perf_tranche['marketing & pr'] = 0.4
perf_tranche['community'] = 0.5
perf_tranche['finance'] = 0.4

perf_score = {}

perf_score['governance'] =  1/3
perf_score['curation'] = 3/3
perf_score['marketing & pr'] = 6/8
perf_score['community'] = 1/2
perf_score['finance'] = 2/3


final_budget = {}
total_final_budget = 0
total_init = 0

for area in init_budget:
  final_budget[area] = round(init_budget[area]*(1-perf_tranche[area]) + init_budget[area]*(perf_tranche[area]*perf_score[area]),2)
  total_final_budget = total_final_budget + final_budget[area]
  total_init = total_init + init_budget[area]

print(final_budget)
print("total final budget = " + str(round(total_final_budget,2)) + " out of " + str(total_init))

{'governance': 1.47, 'curation': 2.5, 'marketing & pr': 2.25, 'community': 1.12, 'finance': 1.3}
total final budget = 8.64 out of 10.0

In [71]:
# READ AND CLEAN COORDINAPE DATA
dfs = {}
voting_members = {}
total_give = {}

path = './coordinape_data/'
files = (file for file in os.listdir(path) 
         if os.path.isfile(os.path.join(path, file)))

for file in files:
    # read data from coordinape files 
  key = re.search('DAO-(.+?)-', file).group(1).lower()
  dfs[key] = pd.read_csv('./coordinape_data/'+ file)

  # calculate voting stats for each area
  voting_members[key] = int(dfs[key]['sent'].astype(bool).sum(axis=0))
  total_give[key] = int(dfs[key]['received'].sum())

  # calculate compensation per area
  dfs[key] = dfs[key].sort_values(by=['received'], ascending = False) # sort
  dfs[key] = dfs[key][['name','address','received']] # select relevant cols
  dfs[key]['percent_comp'] = dfs[key]['received']/total_give[key] # calculate percentage comp.
  dfs[key]['eth_compensation'] = dfs[key]['percent_comp'] * final_budget[key] # calculate actual ETH comp.
  dfs[key] = dfs[key][dfs[key]['eth_compensation'] > 0] # filter people with 0 compensation
  dfs[key]['area'] = key
  dfs[key]['total_budget_of_area'] = final_budget[key]

# prepare area breakdown for reporting
df_export = pd.concat(dfs)

# merge everything and calculate compensation per member
comp_df = pd.concat(dfs)
comp_df = comp_df[['name','address','eth_compensation']]
comp_df = comp_df.groupby(by=['name','address']).sum().reset_index()
comp_df = comp_df.sort_values(by=['eth_compensation'], ascending = False)

print('# of members who voted per area: ' + str(voting_members))
print('total votes per area: ' + str(total_give))
print("total compensated members: " + str(len(comp_df)))

# of members who voted per area: {'community': 15, 'curation': 16, 'finance': 11, 'governance': 15, 'marketing & pr': 16}
total votes per area: {'community': 1868, 'curation': 2100, 'finance': 1376, 'governance': 1672, 'marketing & pr': 2096}
total compensated members: 32

In [72]:
# PRINT VOTES PER MEMBER PER AREA
df_export[['name','total_budget_of_area','received','percent_comp','eth_compensation']]

                                 name  total_budget_of_area  received  \
community      21        claudia#0273                  1.12       363
               46        brileigh.eth                  1.12       240
               10   matthewbrooks.eth                  1.12       234
               37         JoseCactuss                  1.12       221
               6          Lapsus#4632                  1.12       126
...                               ...                   ...       ...
marketing & pr 38         danielhuete                  2.25         5
               24             HugoFaz                  2.25         5
               19  chadwicktyler#3331                  2.25         5
               10       foto.eth#8472                  2.25         5
               14       hddamico#7928                  2.25         5

                   percent_comp  eth_compensation
community      21      0.194325          0.217645
               46      0.128480          0.143897
               10      0.125268          0.140300
               37      0.118308          0.132505
               6       0.067452          0.075546
...                         ...               ...
marketing & pr 38      0.002385          0.005367
               24      0.002385          0.005367
               19      0.002385          0.005367
               10      0.002385          0.005367
               14      0.002385          0.005367

[114 rows x 5 columns]

In [73]:
# PRINT ETH COMPENSATION PER MEMBER FOR THIS MONTH
comp_df[['name','eth_compensation']]

                     name  eth_compensation
10           brileigh.eth          1.459972
23      matthewbrooks.eth          1.306034
15           claudia#0273          1.051241
1             JoseCactuss          0.778228
25            munzmeister          0.631399
3             Lapsus#4632          0.512616
24          mishaderidder          0.481331
5           TrevorTraynor          0.308389
28       samedixsnft#8110          0.242704
27          samcronenberg          0.205335
4           MesutNFT#9591          0.191813
8               b123#2778          0.188688
31                 vcolak          0.165712
11         bthemouth#0088          0.163288
16            danielhuete          0.157271
21             glory#5406          0.146007
7   alexcartagenamex#4215          0.104422
19  ezra | shibboleth.eth          0.086438
17         darkroom.felix          0.075510
29    shanelavalette#2830          0.066353
30           tatiana#6176          0.057575
13     chadwicktyler#3331          0.051244
18        drivenbyboredom          0.047171
22          hddamico#7928          0.036380
0                 HugoFaz          0.033982
20          foto.eth#8472          0.023841
26                nyquist          0.018895
12    carlovanderoer#0512          0.017857
2              Klamt#3962          0.011905
9          blockbird#2283          0.009448
6        Zak_Krevitt#7060          0.005952
14      charlierubin#0001          0.002998

In [114]:
# CALCULATE MONTHLY RANKING

df_rankings = df_export.reset_index()

# This is where we get into a discussion of how exactly to normalize the ranking. The approach I've chosen here is to weigh each member's score by the areas budget, 
# which is equivalent to using their ETH compensation as the score measurement. This way, members who are performing in areas with higher budget (deemed more important) 
# will score higher in the rankings.

df_rankings['normalized_score'] = df_rankings['percent_comp'] * df_rankings['total_budget_of_area']/total_final_budget # score weighted by area's budget
df_rankings = df_rankings[['name','address','normalized_score','area']]
df_rankings = df_rankings.groupby(by=['name','address']).sum()
df_rankings = df_rankings.sort_values(by=['normalized_score'], ascending = False).reset_index()
df_rankings.index = df_rankings.index + 1
df_rankings['percentile'] = df_rankings.index/len(df_rankings)

# Award Conditions
conditions = [
    (df_rankings['percentile'] <= 0.1),
    (df_rankings['percentile'] > 0.1) & (df_rankings['percentile'] <= 0.25),
    (df_rankings['percentile'] > 0.25) & (df_rankings['percentile'] <= 0.5),
    (df_rankings['percentile'] > 0.5) & (df_rankings['percentile'] <= 0.8),
    (df_rankings['percentile'] > 0.8)
]

tier = [ 
    'top 10%',
    'top 25%',
    'top 50%',
    'bottom 50%',
    'bottom 20%'
]

tokens_awarded = [
    0,
    0,
    0,
    0,
    0
]

coordinape = [ 
    20,
    10,
    5,
    0,
    'reset to 100'
]

roles = [
    'Active Member',
    'Active Member',
    'Active Member',
    'No change',
    'Role demotion'
]


df_rankings['tier'] = np.select(conditions, tier)
df_rankings['$RAW Awarded'] = np.select(conditions, tokens_awarded)
df_rankings['coordinape_change'] = np.select(conditions, coordinape)
df_rankings['role_awarded'] = np.select(conditions, roles)


print('Monthly Ranking Awards')
df_rankings[['name','normalized_score', 'percentile', 'tier', '$RAW Awarded', 'coordinape_change', 'role_awarded']]

,name,normalized_score,percentile,tier,$RAW Awarded,coordinape_change,role_awarded
1,brileigh.eth,0.168978,0.03125,top 10%,0,20,Active Member
2,matthewbrooks.eth,0.151161,0.06250,top 10%,0,20,Active Member
3,claudia#0273,0.121671,0.09375,top 10%,0,20,Active Member
4,JoseCactuss,0.090073,0.12500,top 25%,0,10,Active Member
5,munzmeister,0.073079,0.15625,top 25%,0,10,Active Member
6,Lapsus#4632,0.059331,0.18750,top 25%,0,10,Active Member
7,mishaderidder,0.055710,0.21875,top 25%,0,10,Active Member
8,TrevorTraynor,0.035693,0.25000,top 25%,0,10,Active Member
9,samedixsnft#8110,0.028091,0.28125,top 50%,0,5,Active Member
10,samcronenberg,0.023766,0.31250,top 50%,0,5,Active Member
11,MesutNFT#9591,0.022201,0.34375,top 50%,0,5,Active Member
12,b123#2778,0.021839,0.37500,top 50%,0,5,Active Member
13,vcolak,0.019180,0.40625,top 50%,0,5,Active Member
14,bthemouth#0088,0.018899,0.43750,top 50%,0,5,Active Member
15,danielhuete,0.018203,0.46875,top 50%,0,5,Active Member
16,glory#5406,0.016899,0.50000,top 50%,0,5,Active Member
17,alexcartagenamex#4215,0.012086,0.53125,bottom 50%,0,0,No change
18,ezra | shibboleth.eth,0.010004,0.56250,bottom 50%,0,0,No change
19,darkroom.felix,0.008740,0.59375,bottom 50%,0,0,No change
20,shanelavalette#2830,0.007680,0.62500,bottom 50%,0,0,No change
21,tatiana#6176,0.006664,0.65625,bottom 50%,0,0,No change
22,chadwicktyler#3331,0.005931,0.68750,bottom 50%,0,0,No change
23,drivenbyboredom,0.005460,0.71875,bottom 50%,0,0,No change
24,hddamico#7928,0.004211,0.75000,bottom 50%,0,0,No change
25,HugoFaz,0.003933,0.78125,bottom 50%,0,0,No change
26,foto.eth#8472,0.002759,0.81250,bottom 20%,0,reset to 100,Role demotion
27,nyquist,0.002187,0.84375,bottom 20%,0,reset to 100,Role demotion
28,carlovanderoer#0512,0.002067,0.87500,bottom 20%,0,reset to 100,Role demotion
29,Klamt#3962,0.001378,0.90625,bottom 20%,0,reset to 100,Role demotion
30,blockbird#2283,0.001093,0.93750,bottom 20%,0,reset to 100,Role demotion
31,Zak_Krevitt#7060,0.000689,0.96875,bottom 20%,0,reset to 100,Role demotion
32,charlierubin#0001,0.000347,1.00000,bottom 20%,0,reset to 100,Role demotion

In [116]:
# CALCULATE AGGREGATE YEARLY RANKING

# Read and aggregrate past monthly rankings —————————————————————————————————————————————
dfs = {}
voting_members = {}
total_give = {}

path = './outputs/'
files = (file for file in os.listdir(path) 
         if os.path.isfile(os.path.join(path, file)))

past_data = {}

for file in files:
    # read data from past LT comp files
    if 'monthly_comp_rankings' in file:
        past_data[file] = pd.read_excel(path+file)

df_lt_rankings = pd.concat(past_data)
df_lt_rankings = df_lt_rankings[['name','normalized_score']]
df_lt_rankings = df_lt_rankings.groupby(by=['name']).sum().sort_values(by='normalized_score',ascending=False).reset_index()

# Calculate grants —————————————————————————————————————————————
df_lt_rankings.index = df_lt_rankings.index + 1
df_lt_rankings['percentile'] = df_lt_rankings.index/len(df_lt_rankings)

conditions = [
    (df_lt_rankings['percentile'] <= 0.1),
    (df_lt_rankings['percentile'] > 0.1) & (df_lt_rankings['percentile'] <= 0.25),
    (df_lt_rankings['percentile'] > 0.25) & (df_lt_rankings['percentile'] <= 0.5),
    (df_lt_rankings['percentile'] > 0.5) & (df_lt_rankings['percentile'] <= 0.8),
    (df_lt_rankings['percentile'] > 0.8)
]

tier = [ 
    'top 10%',
    'top 25%',
    'top 50%',
    'bottom 50%',
    'bottom 20%'
]

tokens_awarded = [
    1000,
    500,
    150,
    0,
    0
]

coordinape = [ 
    20,
    10,
    5,
    0,
    'reset to 100'
]

roles = [
    'Honorary Member',
    'Core Member',
    'Active Member',
    'No change',
    'Role demotion'
]


df_lt_rankings['tier'] = np.select(conditions, tier)
df_lt_rankings['$RAW Awarded'] = np.select(conditions, tokens_awarded)
df_lt_rankings['coordinape_change'] = np.select(conditions, coordinape)
df_lt_rankings['Role awarded'] = np.select(conditions, roles)

print('Yearly Aggregated Ranking Awards')
print('total $RAW awareded: ' + str(df_lt_rankings['$RAW Awarded'].sum()))
df_lt_rankings

Yearly Aggregated Ranking Awards
total $RAW awareded: 9300

,name,normalized_score,percentile,tier,$RAW Awarded,coordinape_change,Role awarded
1,brileigh.eth,0.517533,0.021277,top 10%,1000,20,Honorary Member
2,matthewbrooks.eth,0.498004,0.042553,top 10%,1000,20,Honorary Member
3,claudia#0273,0.409649,0.063830,top 10%,1000,20,Honorary Member
4,JoseCactuss,0.308912,0.085106,top 10%,1000,20,Honorary Member
5,munzmeister,0.267683,0.106383,top 25%,500,10,Core Member
6,Lapsus#4632,0.215953,0.127660,top 25%,500,10,Core Member
7,lucaspon,0.175459,0.148936,top 25%,500,10,Core Member
8,mishaderidder,0.125372,0.170213,top 25%,500,10,Core Member
9,glory#5406,0.116561,0.191489,top 25%,500,10,Core Member
10,b123#2778,0.114493,0.212766,top 25%,500,10,Core Member
11,ezra | shibboleth.eth,0.103481,0.234043,top 25%,500,10,Core Member
12,tatiana#6176,0.100373,0.255319,top 50%,150,5,Active Member
13,MesutNFT#9591,0.099736,0.276596,top 50%,150,5,Active Member
14,bthemouth#0088,0.094607,0.297872,top 50%,150,5,Active Member
15,TrevorTraynor,0.086726,0.319149,top 50%,150,5,Active Member
16,samcronenberg,0.085800,0.340426,top 50%,150,5,Active Member
17,samedixsnft#8110,0.075898,0.361702,top 50%,150,5,Active Member
18,nyquist,0.060783,0.382979,top 50%,150,5,Active Member
19,darkroom.felix,0.050232,0.404255,top 50%,150,5,Active Member
20,hddamico#7928,0.046754,0.425532,top 50%,150,5,Active Member
21,quimp,0.045801,0.446809,top 50%,150,5,Active Member
22,shanelavalette#2830,0.042508,0.468085,top 50%,150,5,Active Member
23,chadwicktyler#3331,0.040612,0.489362,top 50%,150,5,Active Member
24,Samovarul#6470,0.031887,0.510638,bottom 50%,0,0,No change
25,alexcartagenamex#4215,0.031376,0.531915,bottom 50%,0,0,No change
26,danielhuete,0.030837,0.553191,bottom 50%,0,0,No change
27,HugoFaz,0.030189,0.574468,bottom 50%,0,0,No change
28,vcolak,0.026672,0.595745,bottom 50%,0,0,No change
29,blockbird#2283,0.021537,0.617021,bottom 50%,0,0,No change
30,b_themouth#0088,0.020010,0.638298,bottom 50%,0,0,No change
31,Freddie#0100,0.016850,0.659574,bottom 50%,0,0,No change
32,foto.eth#8472,0.016700,0.680851,bottom 50%,0,0,No change
33,carlovanderoer#0512,0.014177,0.702128,bottom 50%,0,0,No change
34,FramesFL#3512,0.013191,0.723404,bottom 50%,0,0,No change
35,mdr#8647,0.008916,0.744681,bottom 50%,0,0,No change
36,Zak_Krevitt#7060,0.008599,0.765957,bottom 50%,0,0,No change
37,Klamt#3962,0.007370,0.787234,bottom 50%,0,0,No change
38,drivenbyboredom,0.006104,0.808511,bottom 20%,0,reset to 100,Role demotion
39,RobinFriend#7507,0.005774,0.829787,bottom 20%,0,reset to 100,Role demotion
40,Let’s Not Know Us#1036,0.005283,0.851064,bottom 20%,0,reset to 100,Role demotion
41,tommydavidphoto,0.004627,0.872340,bottom 20%,0,reset to 100,Role demotion
42,f1cken,0.004452,0.893617,bottom 20%,0,reset to 100,Role demotion
43,charlierubin#0001,0.003987,0.914894,bottom 20%,0,reset to 100,Role demotion
44,alexandruchitu.eth#6244,0.003217,0.936170,bottom 20%,0,reset to 100,Role demotion
45,MichaMandelberg#1138,0.002809,0.957447,bottom 20%,0,reset to 100,Role demotion
46,TheLoopDigga,0.002082,0.978723,bottom 20%,0,reset to 100,Role demotion
47,M Ram,0.000422,1.000000,bottom 20%,0,reset to 100,Role demotion

In [117]:
# EXPORT RESULTS TO EXCEL
from pathlib import Path
Path("./outputs").mkdir(parents=True, exist_ok=True)

df_export.to_excel("./outputs/"+ month +" - compensation_per_area.xlsx")
comp_df.to_excel("./outputs/"+ month +" - compensation_by_member.xlsx")
df_rankings.to_excel("./outputs/"+ month +" - monthly_comp_rankings.xlsx")
df_lt_rankings.to_excel("./outputs/"+ month +" - LT_comp_rankings.xlsx")